In [48]:
import numpy as np

Задание 2

In [49]:
A = np.array([[1, -2], [3, 0]])
A


array([[ 1, -2],
       [ 3,  0]])

In [50]:
B = np.array([[4, -1], [0, 5]])
B

array([[ 4, -1],
       [ 0,  5]])

In [51]:
C = np.dot(B,A)
C

array([[ 1, -8],
       [15,  0]])

In [52]:
C = np.dot(A,B)
C

array([[  4, -11],
       [ 12,  -3]])

Задание 3

In [53]:
A = np.array([[1, 7], [3, -6]])
A

array([[ 1,  7],
       [ 3, -6]])

In [54]:
B = np.array([[0, 5], [2, -1]])
B

array([[ 0,  5],
       [ 2, -1]])

In [55]:
F = np.array([[2, -4], [1, 1]])
F

array([[ 2, -4],
       [ 1,  1]])

In [56]:
D = 3*A - 2*B + 4*F
D

array([[ 11,  -5],
       [  9, -12]])

Задание № 4

In [57]:
A1 = np.array([[4, 1], [5, -2], [2, 3]])
A1

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [58]:
A1T = A1.T
A1T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [63]:
Corr = np.dot(A1, A1T)
Corr

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [65]:
Cov = np.dot(A1T, A1)
Cov

array([[45,  0],
       [ 0, 14]])

Часть 2

Задание 1.в.

In [66]:
import scipy.linalg

In [68]:
a = np.array([[ 1,  2,  3],
       [ 4, 5,  6],
       [ 7, 8,  9]])

In [71]:
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


Задание 3

In [74]:
b = np.array([[ -2,  7,  -3],
       [ 4, -14,  6],
       [ -3, 7,  13]])

In [75]:
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Определитель:
0


Задание 4

In [76]:
с = np.array([[ 1,  2,  3],
       [ 1, 1,  1],
       [ 2, 3,  4]])

In [77]:
r = np.linalg.matrix_rank(с)
r

2

In [78]:
d = np.array([[ 0,  0,  2, 1],
       [ 0, 0,  2, 2],
       [ 0, 0,  4, 3],
       [ 2, 3,  5, 6]      ])

In [80]:
r1 = np.linalg.matrix_rank(d)
r1

3