In [32]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision = 2, suppress = True)

In [33]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [34]:
U, s, W = np.linalg.svd(A)

In [35]:
V = W.T # Транспонируем матрицу W
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype = float) 
D[np.diag_indices(min(A.shape))] = s
D


array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [36]:
np.dot(V.T,V) # Убедимся, что матрица V ортогональна

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [38]:
np.dot(U.T, U) # Убедимся, что матрица U ортогональна

array([[ 1., -0.,  0.,  0.,  0.],
       [-0.,  1., -0., -0., -0.],
       [ 0., -0.,  1.,  0., -0.],
       [ 0., -0.,  0.,  1., -0.],
       [ 0., -0., -0., -0.,  1.]])

In [39]:
np.dot(np.dot(U, D), V.T) # Проведем проверку

array([[ 1.,  2., -0.],
       [-0.,  0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [ 0.,  1.,  0.]])

In [40]:
#евклидова норма
norm(A, ord = 2)

8.824868854820442

In [41]:
max(s)

8.824868854820448

In [42]:
#нормa Фробениуса
np.linalg.norm(A, ord='fro')

11.045361017187261